export type { ComponentInstance } from '../../core/src/index.js'
export type { DebugPanelTab, DebugPanelOptions, PerformanceMetrics, DebugInfo } from './panel.js'
export { DebugPanel } from './panel.js'
export { DebugManager } from './manager.js'
export type { DebugManagerOptions } from './manager.js'
